apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-pipeline
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-src
      retries: 2
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source

    - name: bld-cmd-image
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: build-task-no-pvc
      params:
        - name: imageTag
          value: "latest"
        - name: imageName
          value: "run-command"
        - name: dockerfile
          value: "CommonPipelineResources/Dockerfile"
        - name: contextPath
          value: "CommonPipelineResources"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-im-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/IntegrationManifests/deploy-im.sh -n cp4i -b {{DEFAULT_BLOCK_STORAGE}} -f {{DEFAULT_FILE_STORAGE}}
      workspaces:
        - name: git-source
          workspace: git-source

    - name: is-cfg-dev
      retries: 2
      runAfter:
        - d-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/create-ace-mq-configuration.sh -n cp4i -c qm-mq-ddd-qm-dev-client -o application-ddd-dev
      workspaces:
        - name: git-source
          workspace: git-source

    - name: wait-im-dev
      retries: 2
      runAfter:
        - d-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: oc wait --for=condition=ready -n {{NAMESPACE}} im ddd-dev --timeout 10m
      workspaces:
        - name: git-source
          workspace: git-source

    - name: bld-is-api
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-api"
        - name: dockerfile
          value: "DrivewayDentDeletion/IntegrationManifests/Dockerfiles/ACE-API.Dockerfile"
        - name: contextPath
          value: "DrivewayDentDeletion/Bar_files/ace-api"
        - name: pvc
          value: "buildah-ace-api"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: bld-is-acme
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-acme"
        - name: dockerfile
          value: "DrivewayDentDeletion/IntegrationManifests/Dockerfiles/ACE-Acme.Dockerfile"
        - name: contextPath
          value: "DrivewayDentDeletion/Bar_files/ace-acme"
        - name: pvc
          value: "buildah-ace-acme"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: bld-is-bernie
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-bernie"
        - name: dockerfile
          value: "DrivewayDentDeletion/IntegrationManifests/Dockerfiles/ACE-Bernie.Dockerfile"
        - name: contextPath
          value: "DrivewayDentDeletion/Bar_files/ace-bernie"
        - name: pvc
          value: "buildah-ace-bernie"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: bld-is-chris
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-chris"
        - name: dockerfile
          value: "DrivewayDentDeletion/IntegrationManifests/Dockerfiles/ACE-Chris.Dockerfile"
        - name: contextPath
          value: "DrivewayDentDeletion/Bar_files/ace-chris"
        - name: pvc
          value: "buildah-ace-chris"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-api-dev
      retries: 2
      runAfter:
        - bld-is-api
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/release-ace-integration-server.sh -n {{NAMESPACE}} -a false -r ddd-dev-ace-api -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/ddd-ace-api:$(params.imageTag) {{TRACING}} -c "[keystore-ddd, policyproject-ddd-dev, serverconf-ddd, setdbparms-ddd, application-ddd-dev]"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-acme-dev
      retries: 2
      runAfter:
        - bld-is-acme
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/release-ace-integration-server.sh -n {{NAMESPACE}} -a false -r ddd-dev-ace-acme -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/ddd-ace-acme:$(params.imageTag) {{TRACING}} -c "[keystore-ddd, policyproject-ddd-dev, serverconf-ddd, setdbparms-ddd, application-ddd-dev]"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-bernie-dev
      retries: 2
      runAfter:
        - bld-is-bernie
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/release-ace-integration-server.sh -n {{NAMESPACE}} -a false -r ddd-dev-ace-bernie -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/ddd-ace-bernie:$(params.imageTag) {{TRACING}} -c "[keystore-ddd, policyproject-ddd-dev, serverconf-ddd, setdbparms-ddd, application-ddd-dev]"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-chris-dev
      retries: 2
      runAfter:
        - bld-is-chris
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/release-ace-integration-server.sh -n {{NAMESPACE}} -a false -r ddd-dev-ace-chris -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/ddd-ace-chris:$(params.imageTag) {{TRACING}} -c "[keystore-ddd, policyproject-ddd-dev, serverconf-ddd, setdbparms-ddd, application-ddd-dev]"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: test-dev
      retries: 2
      runAfter:
        - is-cfg-dev
        - wait-im-dev
        - d-api-dev
        - d-acme-dev
        - d-bernie-dev
        - d-chris-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s ddd -d dev
      workspaces:
        - name: git-source
          workspace: git-source
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dev-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - template:
        ref: dev-triggertemplate

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: dev-event-listener
  name: el-main-trigger-route
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-dev-event-listener
    weight: null
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: dev-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: dev-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: dev-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: git-source
            persistentvolumeclaim:
              claimName: git-source-workspace
        params:
          - name: imageTag
            value: $(uid)
        timeout: "20m"
