apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-apic-pipeline
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-src
      retries: 2
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source

    - name: d-ia-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BASE_URL=${FORKED_REPO%.*}/raw/${BRANCH}
            DDD_ENV='dev'
            /workspace/git-source/DrivewayDentDeletion/Operators/deploy-ia.sh -n {{NAMESPACE}} -b {{DEFAULT_BLOCK_STORAGE}} -f {{DEFAULT_FILE_STORAGE}} -e ${DDD_ENV} -u "${BASE_URL}" -a
      workspaces:
        - name: git-source
          workspace: git-source

    - name: ir-cfg-dev
      retries: 2
      runAfter:
        - d-ia-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/create-ace-mq-configuration.sh -n {{NAMESPACE}} -c qm-mq-ddd-qm-dev-client -o application-ddd-dev
      workspaces:
        - name: git-source
          workspace: git-source

    - name: wait-ia-dev
      retries: 2
      runAfter:
        - d-ia-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: oc wait --for=condition=ready -n {{NAMESPACE}} IntegrationAssembly ddd-dev --timeout 10m
      workspaces:
        - name: git-source
          workspace: git-source

    - name: subscribe-dev
      retries: 2
      runAfter:
        - wait-ia-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            /workspace/git-source/products/bash/apic-subscribe.sh -r apic -n {{NAMESPACE}} -o main-demo -c main-demo-catalog -u main-demo-corp -p {{NAMESPACE}}-product-ddd -a ddd-app -e "ddd-dev-api-endpoint-client-id" -b "/drivewayrepair"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: test-dev
      retries: 2
      runAfter:
        - subscribe-dev
        - ir-cfg-dev
        - wait-ia-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s ddd -d dev -a
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-ia-test
      retries: 2
      runAfter:
        - test-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BASE_URL=${FORKED_REPO%.*}/raw/${BRANCH}
            DDD_ENV='test'
            /workspace/git-source/DrivewayDentDeletion/Operators/deploy-ia.sh -n {{NAMESPACE}} -b {{DEFAULT_BLOCK_STORAGE}} -f {{DEFAULT_FILE_STORAGE}} -e "${DDD_ENV}" -u "${BASE_URL}" -a
      workspaces:
        - name: git-source
          workspace: git-source

    - name: ir-cfg-test
      retries: 2
      runAfter:
        - d-ia-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/create-ace-mq-configuration.sh -n {{NAMESPACE}} -c qm-mq-ddd-qm-test-client -o application-ddd-test
      workspaces:
        - name: git-source
          workspace: git-source

    - name: wait-ia-test
      retries: 2
      runAfter:
        - d-ia-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: oc wait --for=condition=ready -n {{NAMESPACE}} IntegrationAssembly ddd-test --timeout 10m
      workspaces:
        - name: git-source
          workspace: git-source

    - name: subscribe-test
      retries: 2
      runAfter:
        - wait-ia-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            /workspace/git-source/products/bash/apic-subscribe.sh -r apic -n {{NAMESPACE}} -o ddd-demo-test -c ddd-demo-test-catalog -u ddd-demo-test-corp -p {{NAMESPACE}}-product-ddd -a ddd-app -e "ddd-test-api-endpoint-client-id" -b "/drivewayrepair"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: test-test
      retries: 2
      runAfter:
        - subscribe-test
        - ir-cfg-test
        - wait-ia-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s ddd -d test -a
      workspaces:
        - name: git-source
          workspace: git-source
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-apic-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - template:
        ref: test-apic-triggertemplate

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: test-event-listener
  name: el-main-trigger-route
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-test-apic-event-listener
    weight: null
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: test-apic-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: test-apic-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: test-apic-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: git-source
            persistentvolumeclaim:
              claimName: git-source-workspace
        params:
          - name: imageTag
            value: $(uid)
        timeout: "20m"
