#******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2019. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#****
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
    - name: imageName
      type: string
      description: The image name
    - name: dockerfile
      type: string
      description: The dockerfile
    - name: contextPath
      type: string
      description: The context to run the commands
    - name: pvc
      type: string
      description: The PVC to use for layers
  workspaces:
    - name: git-source
  steps:
    - name: build
      image: quay.io/buildah/stable:latest
      securityContext:
        privileged: true
      script: |
        df -h /var/lib/containers
        buildah --storage-driver vfs bud \
          -f /workspace/git-source/$(params.dockerfile) \
          -t image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.imageName):$(params.imageTag) \
          /workspace/git-source/$(params.contextPath)
        buildah --storage-driver vfs push \
          --tls-verify=false \
          image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.imageName):$(params.imageTag)
        df -h /var/lib/containers
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      resources:
        requests:
          memory: "4Gi"
          cpu: "1"
          ephemeral-storage: "5Gi"
        limits:
          ephemeral-storage: "5Gi"
  volumes:
    - name: varlibcontainers
      persistentVolumeClaim:
        claimName: $(params.pvc)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task-no-pvc
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
    - name: imageName
      type: string
      description: The image name
    - name: dockerfile
      type: string
      description: The dockerfile
    - name: contextPath
      type: string
      description: The context to run the commands
  workspaces:
    - name: git-source
  steps:
    - name: build
      image: quay.io/buildah/stable:latest
      securityContext:
        privileged: true
      script: |
        buildah --storage-driver vfs bud \
          -f /workspace/git-source/$(params.dockerfile) \
          -t image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.imageName):$(params.imageTag) \
          /workspace/git-source/$(params.contextPath)
        buildah --storage-driver vfs push \
          --tls-verify=false \
          image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.imageName):$(params.imageTag)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-command
spec:
  params:
    - name: command
      type: string
      description: The command to run
  workspaces:
    - name: git-source
  steps:
    - name: command
      image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/run-command:latest
      script: |
        #!/usr/bin/env bash
        set -e
        echo "Running in bash with \"set -e\""
        echo "Starting command:"
        $(params.command)
