# this task is to push the images that our tested to test namespace
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-push-to-test
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
    - name: imageName
      type: string
      description: The image tag
    - name: pvc
      type: string
      description: The PVC to use for layers
  steps:
    - name: pull-retag-push-to-test
      image: quay.io/openshift/origin-cli:latest
      script: |
        oc tag -n {{NAMESPACE}} $(params.imageName):$(params.imageTag) $(params.imageName):$(params.imageTag)-test

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: api-test-e2e
spec:
  params:
    - name: suffix
      type: string
      description: The suffix for the user and database name
    - name: dddType
      type: string
      description: The ddd demo type
  workspaces:
    - name: git-source
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      script: "/workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s $(params.suffix) -d $(params.dddType) -a"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apic-resource-config
spec:
  params:
    - name: environment
      type: string
      description: environment i.e dev or test
    - name: releaseName
      type: string
      description: release name of the deployment
    - name: releaseScript
      type: string
      description: release name of script
  workspaces:
    - name: git-source
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      script: "/workspace/git-source/products/bash/$(params.releaseScript) -n {{NAMESPACE}} -r $(params.releaseName) -e $(params.environment)"
