apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: api-test-e2e
spec:
  params:
    - name: suffix
      type: string
      description: The suffix for the user and database name
    - name: dddType
      type: string
      description: The ddd demo type
  workspaces:
    - name: git-source
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      script: "/workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s $(params.suffix) -d $(params.dddType)"
