apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-pipeline
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-source
      retries: 2
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source

    - name: fixup-dockerfiles
      retries: 2
      runAfter:
        - clone-git-source
      taskRef:
        name: run-script
      params:
        - name: script
          value: "products/bash/fixup-dockerfiles.sh"
        - name: params
          value: " -n {{NAMESPACE}}"
      workspaces:
        - name: git-source
          workspace: git-source

    # MQ build in dev namespace
    - name: build-mq
      retries: 2
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageName
          value: "mq-ddd"
        - name: imageTag
          value: "latest"
        - name: dockerfile
          value: "MQ.Dockerfile"
        - name: contextPath
          value: ""
        - name: pvc
          value: "buildah-mq"
      workspaces:
        - name: git-source
          workspace: git-source

    # MQ deploy in dev namesapce
    - name: deploy-wait-mq
      retries: 2
      runAfter:
        - build-mq
      taskRef:
        name: run-script
      params:
        - name: script
          value: "products/bash/release-mq.sh"
        - name: params
          # For Dev deploy with tracing enabled and no HA
          value: " -n {{NAMESPACE}} -a false -b {{DEFAULT_BLOCK_STORAGE}} -r mq-ddd-qm-dev -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/mq-ddd:latest {{TRACING}}"
      workspaces:
        - name: git-source
          workspace: git-source

    # build all ace in dev namespace
    - name: build-ace-int-server-ace-api
      retries: 2
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-api"
        - name: dockerfile
          value: "ACE-API.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-api"
        - name: pvc
          value: "buildah-ace-api"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: build-ace-int-server-ace-acme
      retries: 2
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-acme"
        - name: dockerfile
          value: "ACE-Acme.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-acme"
        - name: pvc
          value: "buildah-ace-acme"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: build-ace-int-server-ace-bernie
      retries: 2
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-bernie"
        - name: dockerfile
          value: "ACE-Bernie.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-bernie"
        - name: pvc
          value: "buildah-ace-bernie"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: build-ace-int-server-ace-chris
      retries: 2
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-chris"
        - name: dockerfile
          value: "ACE-Chris.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-chris"
        - name: pvc
          value: "buildah-ace-chris"
      workspaces:
        - name: git-source
          workspace: git-source

    # deploy all ace in dev namespace
    - name: deploy-wait-ace-api
      retries: 2
      runAfter:
        - build-ace-int-server-ace-api
      taskRef:
        name: run-script
      params:
        - name: script
          value: "products/bash/release-ace-integration-server.sh"
        - name: params
          # For Dev deploy with tracing enabled and no HA
          value: "-n {{NAMESPACE}} -a false -r ddd-dev-ace-api -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/ddd-ace-api:$(params.imageTag) {{TRACING}} -d policyproject-ddd-dev"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: deploy-wait-ace-bernie
      retries: 2
      runAfter:
        - build-ace-int-server-ace-bernie
      taskRef:
        name: run-script
      params:
        - name: script
          value: "products/bash/release-ace-integration-server.sh"
        - name: params
          # For Dev deploy with tracing enabled and no HA
          value: "-n {{NAMESPACE}} -a false -r ddd-dev-ace-bernie -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/ddd-ace-bernie:$(params.imageTag) {{TRACING}} -d policyproject-ddd-dev"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: deploy-wait-ace-acme
      retries: 2
      runAfter:
        - build-ace-int-server-ace-acme
      taskRef:
        name: run-script
      params:
        - name: script
          value: "products/bash/release-ace-integration-server.sh"
        - name: params
          # For Dev deploy with tracing enabled and no HA
          value: "-n {{NAMESPACE}} -a false -r ddd-dev-ace-acme -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/ddd-ace-acme:$(params.imageTag) {{TRACING}} -d policyproject-ddd-dev"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: deploy-wait-ace-chris
      retries: 2
      runAfter:
        - build-ace-int-server-ace-chris
      taskRef:
        name: run-script
      params:
        - name: script
          value: "products/bash/release-ace-integration-server.sh"
        - name: params
          # For Dev deploy with tracing enabled and no HA
          value: "-n {{NAMESPACE}} -a false -r ddd-dev-ace-chris -i image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/ddd-ace-chris:$(params.imageTag) {{TRACING}} -d policyproject-ddd-dev"
      workspaces:
        - name: git-source
          workspace: git-source
